description: |
  API to control health check shields feature

/:
  description: |
    List all health check shields
  get:
    description: |
      Lists all health check shields.
      Note that some shields could already be expired because the purge is done periodically.
    responses:
      200:
        description: |
          Json array containing the task id, shield name, and the timestamp when it will expire.
        body:
          application/json:
            type: healthCheck.HealthCheckShield[]
            example: !include examples/health-check-shield-get.json
      403:
        description: |
          Health check shield API is disabled.

/{taskId}:
  description: |
    List all health check shields of the task
  get:
    description: |
      Lists all health check shields of the task.
      Note that some shields could already be expired because the purge is done periodically.
    responses:
      200:
        description: |
          Json array containing the task id, shield name, and the timestamp when it will expire.
        body:
          application/json:
            type: healthCheck.HealthCheckShield[]
            example: !include examples/health-check-shield-get.json
      403:
        description: |
          Health check shield API is disabled.

/{taskId}/{shieldName}:
  description: |
    Create, update, or delete a health check shield
  uriParameters:
    taskId:
      type: strings.TaskId
      description: |
        Id of the task, as displayed in the Marathon UI
    shieldName:
      type: string
      description: |
        The name of the shield. 
        Allows to define multiple shields for a single task as well as to distinguish who put the shield
  get:
    description: |
      If a shield with this name is defined for this task id, returns the info about this shield.
    responses:
      200:
        description: |
          Json object containing the task id, shield name, and the timestamp when it will expire.
        body:
          application/json:
            type: healthCheck.HealthCheckShield
            example: !include examples/health-check-shield-get-single.json
      403:
        description: |
          Health check shield API is disabled.
      404:
        description: |
          Health check with this name and task id does not exist
  put:
    description: |
      Create or update the shield for the specified task.
      The shield prevents Marathon from killing the task in case the health check is red.
      The primary usage is troubleshooting scenarios when the app is unresponsive, for instance taking a memory snapshot.
      Note that the shield operates on task level. After the corresponding Mesos container is gone the shield is useless.
      Marathon could still kill the instance for another reason like deployment.
      Mesos health checks are not supported as Mesos would kill the app without asking Marathon.
      Multiple shields for the same application work in parallel. The app is protected until all of the shields are deleted or expired.
    is: [ secured ]
    queryParameters:
      duration:
        required: false
        description: |
          For how long the shield should be enabled
        type: string
        default: 30 minutes
    responses:
      200:
        description: |
          The shield was successfully created or updated.
      400:
        description: |
          The duration is larger than configured maximum.
      403:
        description: |
          Rights are not sufficient or the health check shield API is disabled.
      404:
        description: |
          The task id points to the non-existent application.

  delete:
    description: |
      Deletes previously created shield.
      The response code will still be <code>200</code> even if the shield didn't exist.
    is: [ secured ]
    responses:
      200:
        description: |
          The shield was deleted successfully.
      403:
        description: |
          Rights are not sufficient or the health check shield API is disabled.
